version: '3.8'

services:
  web:
    build: .
    image: php:8.0-apache
    container_name: Memoire_app
    volumes:
      - .:/var/www/html
    ports:
      - "7000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=LM
      - DB_USER=root
      - DB_PASSWORD=lila

  db:
    image: mysql:5.7
    container_name: Memoire_db
    volumes:
      - db_data:/var/lib/mysql
      - ./lm.sql:/docker-entrypoint-initdb.d/lm.sql
     
    environment:
      MYSQL_ROOT_PASSWORD: lila
      MYSQL_DATABASE: LM
     

volumes:
  db_data:
